---
title: "From spaceranger to h5mu"
namespace: "Convert"
description: "Converts the output bundle from spaceranger into an h5mu file"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `from_spaceranger_to_h5mu`  
Namespace: `convert`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline_spatial/blob/v0.5.0/src/convert/from_spaceranger_to_h5mu/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline_spatial \
  -r v0.5.0 -latest \
  -main-script target/nextflow/convert/from_spaceranger_to_h5mu/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline_spatial \
  -r v0.5.0 -latest \
  -profile docker \
  -main-script target/nextflow/convert/from_spaceranger_to_h5mu/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name      |Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |Attributes                                        |
|:----------|:--------------------------------------------------|:--------------------|
|`--input` |Convert spatial data resulting from Aviti Teton sequencers that have been processed by the Element Biosciences cells2stats workflow to H5MU format.  This component processes cells2stats count matrices to create a standardized H5MU file for downstream analysis.  The component reads: - Parquet file containing the count matrix and metadata - Panel.json with target and batch information  And outputs an H5MU file with: - Count data as the main .X matrix - Spatial coordinates in obsm - Cell Paint intensities in obsm (optional) - Nuclear count data as a layer (optional) - CellProfiler morphology metrics in obsm (optional) - Unassigned targets in obsm (optional) |`file`, required, example: `"spaceranger_output"` |


### Outputs

|Name                   |Description                                                                |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output`             |Output h5mu file.                                                          |`file`, example: `"output.h5mu"`           |
|`--modality`           |Name of the modality under which to store the data.                        |`string`, default: `"rna"`                 |
|`--uns_metrics`        |Name of the .uns slot under which to QC metrics (if any).                  |`string`, default: `"metrics_spaceranger"` |
|`--uns_probe_set`      |Name of the .uns slot under which to store probe set information (if any). |`string`, default: `"probe_set"`           |
|`--obsm_coordinates`   |Name of the .obsm slot under which to store the cell centroid coordinates. |`string`, default: `"spatial"`             |
|`--output_type`        |Which Spaceranger output to use for converting to h5mu.                    |`string`, default: `"filtered"`            |
|`--output_compression` |Compression to use when writing the h5mu file.                             |`string`                                   |

## Authors


  * Dorien Roosen [{{< fa brands github >}}](https://github.com/dorien-er) [{{< fa brands linkedin >}}](https://linkedin.com/in/dorien-roosen) (maintainer)

