---
title: "Compress h5mu"
namespace: "Compression"
description: "Compress a MuData file."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `compress_h5mu`  
Namespace: `compression`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.2.0/src/compression/compress_h5mu/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::




## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.2.0 -latest \
  -main-script target/nextflow/compression/compress_h5mu/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.2.0 -latest \
  -profile docker \
  -main-script target/nextflow/compression/compress_h5mu/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                   |Description                                                                                                    |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--input`              |Path to the input .h5mu.                                                                                       |`file`, required, example: `"input.h5mu"`  |
|`--output`             |location of output file.                                                                                       |`file`, required, example: `"output.h5mu"` |
|`--output_compression` |Compression format to use for the output AnnData and/or Mudata H5 files. By default no compression is applied. |`string`, example: `"gzip"`                |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (maintainer)

