---
title: "Split modalities"
namespace: "Dataflow"
description: "Split the modalities from a single .h5mu multimodal sample into seperate .h5mu files."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `split_modalities`  
Namespace: `dataflow`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.2.0/src/dataflow/split_modalities/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::




## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.2.0 -latest \
  -main-script target/nextflow/dataflow/split_modalities/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.2.0 -latest \
  -profile docker \
  -main-script target/nextflow/dataflow/split_modalities/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                   |Description                                                                                                    |Attributes                                                          |
|:----------|:--------------------------------------------------|:--------------------|
|`--input`              |Path to a single .h5mu file.                                                                                   |`file`, required, default: `"sample_path"`, example: `"input.h5mu"` |
|`--output`             |Output directory containing multiple h5mu files.                                                               |`file`, required, example: `"/path/to/output"`                      |
|`--output_types`       |A csv containing the base filename and modality type per output file.                                          |`file`, required, example: `"types.csv"`                            |
|`--output_compression` |Compression format to use for the output AnnData and/or Mudata H5 files. By default no compression is applied. |`string`, example: `"gzip"`                                         |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (maintainer)

  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (contributor)

