---
title: "Filter with counts"
namespace: "Filter"
description: "Filter scRNA-seq data based on the primary QC metrics."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `filter_with_counts`  
Namespace: `filter`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.2.0/src/filter/filter_with_counts/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::


This is based on both the UMI counts, the gene counts 
and the mitochondrial genes (genes starting with mt/MT)

## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.2.0 -latest \
  -main-script target/nextflow/filter/filter_with_counts/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.2.0 -latest \
  -profile docker \
  -main-script target/nextflow/filter/filter_with_counts/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name         |Description                                                                                                  |Attributes                                |
|:----------|:--------------------------------------------------|:--------------------|
|`--input`    |Input h5mu file                                                                                              |`file`, required, example: `"input.h5mu"` |
|`--modality` |Which modality from the input MuData file to process.                                                        |`string`, default: `"rna"`                |
|`--layer`    |Location of the count matrix. If specified, will be used to select a key from .layers, otherwise .X is used. |`string`, example: `"raw_counts"`         |


### Outputs

|Name                   |Description                                                                                                    |Attributes                                |
|:----------|:--------------------------------------------------|:--------------------|
|`--output`             |Output h5mu file.                                                                                              |`file`, example: `"output.h5mu"`          |
|`--do_subset`          |Whether to subset before storing the output.                                                                   |`boolean_true`                            |
|`--obs_name_filter`    |In which .obs slot to store a boolean array corresponding to which observations should be removed.             |`string`, default: `"filter_with_counts"` |
|`--var_name_filter`    |In which .var slot to store a boolean array corresponding to which variables should be removed.                |`string`, default: `"filter_with_counts"` |
|`--output_compression` |Compression format to use for the output AnnData and/or Mudata H5 files. By default no compression is applied. |`string`, example: `"gzip"`               |


### Arguments

|Name                   |Description                                 |Attributes                    |
|:----------|:--------------------------------------------------|:--------------------|
|`--min_counts`         |Minimum number of counts captured per cell. |`integer`, example: `200`     |
|`--max_counts`         |Maximum number of counts captured per cell. |`integer`, example: `5000000` |
|`--min_genes_per_cell` |Minimum of non-zero values per cell.        |`integer`, example: `200`     |
|`--max_genes_per_cell` |Maximum of non-zero values per cell.        |`integer`, example: `1500000` |
|`--min_cells_per_gene` |Minimum of non-zero values per gene.        |`integer`, example: `3`       |

## Authors


  * Dries De Maeyer [{{< fa brands github >}}](https://github.com/ddemaeyer) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-de-maeyer-b46a814) (author)

  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (maintainer, author)

