---
title: "Remove modality"
namespace: "Filter"
description: "Remove a modality from a .h5mu file"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `remove_modality`  
Namespace: `filter`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.2.0/src/filter/remove_modality/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.2.0 -latest \
  -main-script target/nextflow/filter/remove_modality/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.2.0 -latest \
  -profile docker \
  -main-script target/nextflow/filter/remove_modality/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                   |Description                                                                                                    |Attributes                                      |
|:----------|:--------------------------------------------------|:--------------------|
|`--input`              |Input h5mu file                                                                                                |`file`, required, example: `"input.h5mu"`       |
|`--modality`           |Name(s) of the modality to remove                                                                              |List of `string`, required, multiple_sep: `";"` |
|`--output`             |Output h5mu file.                                                                                              |`file`, example: `"output.h5mu"`                |
|`--output_compression` |Compression format to use for the output AnnData and/or Mudata H5 files. By default no compression is applied. |`string`, example: `"gzip"`                     |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (maintainer)

